[package]
name = "sap0bombado/create-player-data"
description = "Fork of dataServiceTyped from leifstout/dataservicetyped"
version = "1.0.5"
license = "MIT"
authors = ["sap0bombado"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
    "src",
    "src/*",
    "default.project.json",
    "wally.lock",
    "wally.toml",
    "LICENSE",
]

[dependencies]
signal = "leifstout/signal@2.0.0"
Networker = "leifstout/networker@0.3.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"

